CREATE SCHEMA IF NOT EXISTS OrdensServico;
USE OrdensServico;

CREATE TABLE IF NOT EXISTS Maquina(
  id INT NOT NULL AUTO_INCREMENT,
  nome3 VARCHAR(50) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Setor(
  id INT NOT NULL AUTO_INCREMENT,
  nome2 VARCHAR(50) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Usuario(
  id INT NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(50) NOT NULL,
  senha VARCHAR(50) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  telefone VARCHAR(50) NOT NULL,
  setor_id INT NOT NULL,
  statos VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_Usuario_Setor FOREIGN KEY (setor_id)
  REFERENCES Setor(id) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Ordem(
  id INT NOT NULL AUTO_INCREMENT,
  maquina_id INT NOT NULL,
  problema VARCHAR(200) NOT NULL,
  causa VARCHAR(200),
  solucao VARCHAR(200),
  comentario VARCHAR(200),
  tempo DOUBLE,
  usuario INT,
  PRIMARY KEY (id),
  CONSTRAINT fk_Ordem_Maquina FOREIGN KEY (maquina_id)
  REFERENCES Maquina(id) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB;